version: '3.9'

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chatapp
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - chatnet

  server:
    build: ./server
    restart: always
    environment:
      DB_HOST: db
      DB_USER: chatuser
      DB_PASSWORD: chatpass
      DB_NAME: chatapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - chatnet

  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - chatnet

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - chatnet

volumes:
  db_data:
  ollama_data:

networks:
  chatnet:
